### ISSUE TITLE
运行后等待时间过长

### ISSUE THREAD

**Issue by Rebiah** [smartgrass/AutoPcr#12]
旧版点运行后很短时间就可以正常使用
更新新版本运行后需要等待很久 cmd窗口才开始有动作
请问这个是个例吗 台式机和笔记本都存在 不过配置也比较旧了

**Comment by smartgrass** [comment]
看看截图?是哪个版本?

**Comment by Rebiah** [comment]
![2cd765dab4e481dc.jpg](https://github.com/smartgrass/AutoPcr/assets/26707515/4ad2f309-4059-4f04-8b81-ff70c65101a7)

是12号通过微云下载的7.1 包括刚才微云的fix也一样
台式机6500 单条16G内存
笔记本7300HQ 24G内存

**Comment by smartgrass** [comment]
7.1那个版本其实加了个文字识别，很重。
7.0版本版本就不会了吧

**Comment by Rebiah** [comment]
好的感谢大佬 我更新前应该是久远的6.x版 这就去换v7.0试试


顺便刚才fix版本出现了报错
=====Again======
AutoTask
C:\Users\shuai\Desktop\AutoPcr6.2\task/menu.png
match : task/menu.png None
False
Ship >>  task/menu.png
C:\Users\shuai\Desktop\AutoPcr6.2\task/noSound.png
match : task/noSound.png None
False
Ship >>  task/noSound.png
C:\Users\shuai\Desktop\AutoPcr6.2\task/skipBtn.png
match : task/skipBtn.png {'result': (589.5, 434.0), 'rectangle': ((484, 407), (484, 461), (695, 407), (695, 461)), 'confidence': 0.8553755283355713}
Traceback (most recent call last):
  File "AutoPcr4.0.py", line 1627, in <module>
  File "AutoPcr4.0.py", line 1616, in RunAutoPcr
  File "AutoPcr4.0.py", line 1367, in DailyTasks
  File "AutoPcr4.0.py", line 1158, in OnAutoTask
  File "AutoPcr4.0.py", line 1158, in OnAutoTask
  File "AutoPcr4.0.py", line 1158, in OnAutoTask
  [Previous line repeated 37 more times]
  File "AutoPcr4.0.py", line 1142, in OnAutoTask
  File "AutoPcr4.0.py", line 425, in IsHasImg
  File "AutoPcr4.0.py", line 443, in WaitToClickImg
  File "AutoPcr4.0.py", line 334, in SavaShoot
  File "PIL\Image.py", line 2410, in save
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\shuai\\Desktop\\AutoPcr6.2\\temp.png'
[17188] Failed to execute script 'AutoPcr4.0' due to unhandled exception!

**Comment by smartgrass** [comment]
这个是io流卡住了，应该是意外情况

**Comment by Rebiah** [comment]
换v70就正常了 谢谢大佬
